#!/usr/bin/bash

function create_table1()
{	
clear
## Table creation

### check if the db selected or not
	if [[ ! -z $SelectedDB ]]
		then
		cd ~/DB/$SelectedDB
	
	read -p "please enter the table name : " table_name
	if [[ $table_name =~ ^[a-zA-Z0-9]+$ ]]
	then
		if [[ -e ~/DB/$SelectedDB/$table_name ]]
		then
			if [[ ! -z $table_name ]]
			then
			echo "Table Is slected !!"
			fi
			

		else 
			touch $table_name
			touch ".meta$table_name"
			echo "table is created successfully"


## creation of cols

read -p "Please enter number of cols : " col_num
	
	if [[ $col_num =~ ^[1-9]$ ]]
		then

			echo "you slected $col_num "
			echo "please be careful !"
			echo "the first col is designed to be the pk"	
		for (( i=0;i<$col_num;i++))
		do

				
			read -p "PLease enter the col name : " col_name
			if [[ $col_name =~ ^[a-z]+[a-z_]*$ ]]
			then

result=$(awk -v col_nam=$col_name '

BEGIN{FS=":";count=0}

{if($1==col_nam){x++}}

END{print x}

' ~/DB/$SelectedDB/".meta$table_name")

if [[ $result -eq 1 ]]

then
	echo "this COL IS REPEATED"
	echo "table is deleted"
	rm ~/DB/$SelectedDB/".meta$table_name"
	rm ~/DB/$SelectedDB/$table_name
	break
	
fi

		read -p "please enter the col type  int or char: " col_type
			if [[ $col_type = "int" || $col_type = "char" ]]
			then
			
			if [[ $i -eq 0 ]]
			then
			echo "$col_name:$col_type:pk" >> ".meta$table_name"
			echo -n "$col_name:" >> "$table_name"
			else

			echo "$col_name:$col_type" >> ".meta$table_name"
			echo -n "$col_name:" >> "$table_name"
			fi
			else
				echo "please select int or char or date only"
			
			fi
			
			else 
				echo "please enter a valid name!"
			
			fi 

		done
		# then truncate the last charachter which is :
		truncate -s -1 "$table_name"
		
		#start in a newline 
		echo "" >> "$table_name"
		
		#cat $table_name | echo{0:-1} >> $table_name
		

		else
			echo "please enter valid col num (from 1 -- 9)"
		fi
		
		fi
	else 
		echo "please enter a valid name"
		#break
	fi
	
else
	echo "please select the DB FIRST"	

fi


}


#!/usr/bin/bash

function create_table ()
{   
clear
## Table creation

### check if the db is selected or not
    if [[ ! -z $SelectedDB ]]; then
        cd ~/DB/$SelectedDB
    
        read -p "Please enter the table name: " table_name
        if [[ $table_name =~ ^[a-zA-Z0-9]+$ ]]; then
            if [[ -e ~/DB/$SelectedDB/$table_name ]]; then
                echo "Table already exists!"
            else 
                touch $table_name
                touch ".meta$table_name"
                echo "Table is created successfully."

                ## creation of columns
                read -p "Please enter the number of columns: " col_num

                if [[ $col_num =~ ^[1-9]$ ]]; then
                    echo "You selected $col_num columns."
                    echo "The first column is designed to be the PK."

                    for (( i=0; i<$col_num; i++)); do
                        # Loop for column name validation
                        while true; do
                            read -p "Please enter the column name: " col_name
                            if [[ $col_name =~ ^[a-z]+[a-z_]*$ ]]; then
                                # Check if the column name already exists
                                result=$(awk -v col_nam=$col_name '
                                BEGIN {FS=":"; count=0}
                                {if($1==col_nam) count++}
                                END {print count}
                                ' ~/DB/$SelectedDB/".meta$table_name")

                                if [[ $result -eq 0 ]]; then
                                    break
                                else
                                    echo "This column name is already used. Please choose another name."
                                fi
                            else
                                echo "Please enter a valid column name! (lowercase letters and underscores only)"
                            fi
                        done

                        # Loop for column type validation
                        while true; do
                            read -p "Please enter the column type (int, char, or date): " col_type
                            if [[ $col_type == "int" || $col_type == "char" || $col_type == "date" ]]; then
                                if [[ $i -eq 0 ]]; then
                                    echo "$col_name:$col_type:pk" >> ".meta$table_name"
                                    echo -n "$col_name:" >> "$table_name"
                                else
                                    echo "$col_name:$col_type" >> ".meta$table_name"
                                    echo -n "$col_name:" >> "$table_name"
                                fi
                                break
                            else
                                echo "Please enter a valid column type (int, char, or date)!"
                            fi
                        done

                    done

                    # Remove the last colon
                    truncate -s -1 "$table_name"
                    
                    # Start a new line for the new record
                    echo "" >> "$table_name"

                else
                    echo "Please enter a valid column number (1-9)."
                fi
            fi
        else 
            echo "Please enter a valid table name!"
        fi

    else
        echo "Please select a database first."
    fi
}

create_table




#create_table
